### ISSUE TITLE
Where should documentation live?

### ISSUE THREAD

**Issue by holingpoon** [NYPL/engineering-general#52]
I've been staring at some old documentation, and these pages are everywhere: On Confluence via Atlassian Cloud, on confluence.nypl, various Google Docs, etc. Our newest spot was to park the documentation on GitHub Wiki pages. Having a discussion with @nonword, he pointed out that the search function on the Wiki is broken. I was on the track of thought that maybe if we ever have to move our repos again somewhere else, we will lose the GitHub Wiki pages because it is specific to GitHub.

I have a suggestion: I think it'll make more sense to embed documentation as part of the repos, e.g. a `doc` or `docs` folder in the code repo, and park all our documentation written in MarkDown that is somehow outside of README. That way the file structure is **vendor-agnostic**, we also have a plus that most repo management vendors such as BitBucket and GitHub would parse MarkDown files.

**Comment by nonword** [comment]
I fully support this. Vendor agnosticism - plus Github clearly does not care about their Wikis. Perhaps a PR is in order to https://github.com/NYPL/engineering-general/blob/master/standards/documentation.md to specify what documentation `MUST` exist at the root level (e.g. `README.md`, `LICENSE.md`), and what documentation `SHOULD`/`MUST` live in `docs/` (e.g. `docs/extended-discussion-of-architectural-choices.md`, `docs/architectural-diagram.svg`, `docs/swagger.[version].json`)

**Comment by nodanaonlyzuul** [comment]
I am happy with docs living along with the application.
It's a shame that GH has invested so little in their wiki functionality considering how potentially powerful it is that the wiki itself, is also a [clone-able git repo](https://gist.github.com/subfuzion/0d3f19c4f780a7d75ba2).
