### ISSUE TITLE
Broken links / housekeeping

### ISSUE THREAD

**Issue by mattkoch614** [NYPL/engineering-general#98]
Several links in the `README.md` file are broken, namely:

1. `Coding Style/Javascript`
2. `Coding Style/Python`
3. `Coding Style/Ruby on Rails`
4. `Coding Style/PHP`
5. `Production Readiness` (was this meant to link to https://github.com/NYPL/engineering-general/blob/main/standards/deployment.md#production-readiness?)

In addition, since this Repo builds out a GitHub pages site here: https://nypl.github.io/engineering-general/ it would be nice to embed that link directly into the `README.md` file for folks to read the information there, if they wish.

**Comment by mattkoch614** [comment]
@mwbenowitz / NYPL digital folks, do these items warrant an issue or should we just drop?

**Comment by mwbenowitz** [comment]
@mattkoch614 I think that it definitely is worth looking into, especially for JS, Python and Ruby. PHP we can probably drop because if we come across it in our codebases we should be looking to drop it.

That production readiness page is pretty out of date, I don't know any team that has that kind of formal review as part of their process (maybe we should?). I'm not sure of what the generally accepted best practice is there either.

As for adding that link I'm in favor!
